# Generated by Django 4.2 on 2023-04-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0002_rename_post_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
