# Generated by Django 4.2 on 2023-05-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0008_brand_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='invenotry_id',
            new_name='inventory_id',
        ),
    ]
