# Generated by Django 4.2 on 2023-05-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0009_rename_category_id_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_id',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.IntegerField(default=0, verbose_name=((0, 'Out of Stock'), (1, 'In Stock'))),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
