# Generated by Django 4.2 on 2023-05-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0011_alter_product_stock_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_id']},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['discount_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'ordering': ['category_id'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
