# Generated by Django 4.2 on 2023-05-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0013_rename_cartitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
