# Generated by Django 4.2 on 2023-06-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0016_alter_discount_discount_amount_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('Available in the store', 'Out of Stock'), ('Out of stock', 'In Stock')], default='Available in the store', max_length=64),
        ),
    ]
