# Generated by Django 4.2 on 2023-06-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0017_alter_product_price_alter_product_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='omg.discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('Available in the store', '1'), ('Out of stock', '0')], default='Available in the store', max_length=64),
        ),
    ]
