# Generated by Django 4.2 on 2023-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0018_alter_product_discount_id_alter_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.FloatField(null=True),
        ),
    ]
