# Generated by Django 4.2 on 2023-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0019_product_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='Available in the store', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
