# Generated by Django 4.2 on 2023-06-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0023_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
    ]
