# Generated by Django 4.2 on 2023-06-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0024_remove_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Your order has been delivered', '3'), ('Your order is in transit', '2'), ('Your order has been proceeded', '1'), ('Your order has been recieved', '0')], default='Available in the store', max_length=64),
        ),
    ]
