# Generated by Django 4.2 on 2023-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omg', '0025_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Your order has been delivered', '3'), ('Your order is in transit', '2'), ('Your order has been proceeded', '1'), ('Your order has been recieved', '0')], default='Your order has been recieved', max_length=64),
        ),
    ]
