# Generated by Django 4.1.7 on 2023-03-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(default='Some comment', max_length=500),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
