# Generated by Django 4.1.7 on 2023-03-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
